# DevSecOps/.checkov.yml - Checkov configuration for IAM Dashboard

# Enable these frameworks
framework:
  - terraform
  - kubernetes
  - cloudformation
  - dockerfile

# Download external Terraform modules when scanning
download-external-modules: true

# Skip common directories (use repeated skip-path, not skip_paths)
skip-path:
  - .terraform
  - .git
  - node_modules
  - dist
  - build
  - .next
  - logs
  - data

# Fail the run if checks fail (strict gate)
# (If you later want PR-only soft fail, we’ll handle that in workflow conditionals.)
soft-fail: false

# Output verbosity
quiet: false

# Skip these checks (wildcard IAM handled by OPA)
skip-check:
  - CKV_AWS_1
  - CKV_AWS_2
  - CKV_AWS_3
  - CKV_AWS_309 # API Gateway Authorization type. Ignored temporarily until Cognito is added

# Optional: keep summary at top
summary-position: top
