# .checkov.yml - Checkov configuration for IAM Dashboard
framework:
  - terraform
  - kubernetes
  - cloudformation
  - dockerfile

download_external_modules: true

skip_paths:
  - .terraform
  - .git
  - node_modules
  - dist
  - build
  - .next
  - logs
  - data

soft_fail_on: false
quiet: false

skip_checks:
  - CKV_AWS_1   # wildcard actions (handled by your OPA rules)
  - CKV_AWS_2   # wildcard resources (OPA)
  - CKV_AWS_3   # wildcard principals (OPA)