# Gitleaks configuration for IAM Dashboard
# This file configures secret detection rules

[gitleaks]
# Enable all rules
enable-all-rules = true

# Exclude specific file patterns
exclude-patterns = [
    "*.md",
    "*.txt",
    "*.log",
    "*.json",
    "*.yml",
    "*.yaml",
    "node_modules/**",
    ".git/**",
    "vendor/**",
    "*.lock",
    "*.sum"
]

# Exclude specific directories
exclude-dirs = [
    ".git",
    "node_modules",
    "vendor",
    "dist",
    "build",
    ".next",
    ".nuxt"
]

# Exclude specific files
exclude-files = [
    "package-lock.json",
    "yarn.lock",
    "go.sum",
    "Pipfile.lock"
]

# Custom rules for IAM Dashboard
[[rules]]
id = "iam-dashboard-custom"
description = "Custom IAM Dashboard secret patterns"
regex = '''(?i)(aws_access_key_id|aws_secret_access_key|aws_session_token|api_key|secret_key|private_key)'''
tags = ["iam", "aws", "secret"]

[[rules]]
id = "jwt-token"
description = "JWT Token"
regex = '''eyJ[A-Za-z0-9_-]*\.[A-Za-z0-9_-]*\.[A-Za-z0-9_-]*'''
tags = ["jwt", "token"]

[[rules]]
id = "database-url"
description = "Database URL"
regex = '''(mysql|postgres|mongodb)://[^\s]+'''
tags = ["database", "url"]

# Exclude common false positives
[[rules]]
id = "exclude-false-positives"
description = "Exclude false positives"
regex = '''(example|test|dummy|placeholder|your_.*_here)'''
tags = ["exclude"]
