# DevSecOps/.gitleaks.toml - Optimized for IAM Dashboard
[gitleaks]
# Use specific rules instead of all rules to reduce false positives
enable-all-rules = false

# Exclude patterns for common false positives
exclude-patterns = [
    "*.md",
    "*.txt", 
    "*.log",
    "*.json",
    "*.yml",
    "*.yaml",
    "node_modules/**",
    ".git/**",
    "vendor/**",
    "*.lock",
    "*.sum",
    "dist/**",
    "build/**",
    ".next/**",
    ".terraform/**",
    "*.tfstate",
    "*.tfplan",
    ".gitignore",
    "README.md",
    "env.example",
    "*.example",
    "docs/**",
    "DevSecOps/opa-policies/**",
    "docker-compose.yml",
    "config/grafana/provisioning/datasources/datasources.yml",
    "docs/SCANNERS.md"
]

# Exclude specific directories
exclude-dirs = [
    ".git",
    "node_modules",
    "vendor",
    "dist",
    "build",
    ".next",
    ".terraform",
    "logs",
    "data",
    "docs",
    "DevSecOps/opa-policies"
]

# Exclude specific files
exclude-files = [
    "package-lock.json",
    "yarn.lock",
    "go.sum",
    "Pipfile.lock",
    "*.tfstate",
    "*.tfplan",
    "env.example",
    "README.md",
    "docs/**/*.md",
    "docker-compose.yml",
    "config/grafana/provisioning/datasources/datasources.yml",
    "docs/SCANNERS.md"
]

# Enable only essential security rules
[[rules]]
id = "aws-access-key"
description = "AWS Access Key"
regex = '''AKIA[0-9A-Z]{16}'''
tags = ["aws", "key"]

[[rules]]
id = "aws-secret-key"
description = "AWS Secret Key"
regex = '''(?i)aws_secret_access_key\s*=\s*['\"][A-Za-z0-9/+=]{40}['\"]'''
tags = ["aws", "secret"]

[[rules]]
id = "github-token"
description = "GitHub Token"
regex = '''ghp_[0-9a-zA-Z]{36}'''
tags = ["github", "token"]

[[rules]]
id = "jwt-token"
description = "JWT Token"
regex = '''eyJ[A-Za-z0-9_-]*\.[A-Za-z0-9_-]*\.[A-Za-z0-9_-]*'''
tags = ["jwt", "token"]