name: DevSecOps Security Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run security scans daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  security-scan:
    runs-on: ubuntu-latest
    name: Security Scan
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history for Gitleaks

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # Gitleaks - Secret Detection
    - name: Run Gitleaks
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}

    # Checkov - Infrastructure Security
    - name: Run Checkov
      uses: bridgecrewio/checkov-action@master
      with:
        directory: .
        framework: all
        output_format: sarif
        output_file_path: reports/checkov.sarif
        soft_fail: true
        download_external_modules: true
        skip_check: CKV_AWS_1,CKV_AWS_2  # Add any checks to skip
        check: CKV_AWS_1,CKV_AWS_2,CKV_AWS_3,CKV_AWS_4,CKV_AWS_5

    # OPA - Policy as Code
    - name: Install OPA
      run: |
        curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
        chmod +x opa
        sudo mv opa /usr/local/bin/

    - name: Run OPA Policy Tests
      run: |
        opa test policies/ --verbose
      continue-on-error: true

    - name: Run OPA Security Policies
      run: |
        opa eval --data policies/security.rego --input . --format pretty
      continue-on-error: true

    # Upload security reports
    - name: Upload Checkov SARIF
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: reports/checkov.sarif
        category: checkov

    # Security summary
    - name: Security Scan Summary
      if: always()
      run: |
        echo "## Security Scan Results" >> $GITHUB_STEP_SUMMARY
        echo "### Tools Executed:" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Gitleaks (Secret Detection)" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Checkov (Infrastructure Security)" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ OPA (Policy as Code)" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Check the Security tab for detailed results." >> $GITHUB_STEP_SUMMARY

  dependency-scan:
    runs-on: ubuntu-latest
    name: Dependency Security Scan
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi

    - name: Run Safety (Python dependencies)
      uses: lucas-clemente/safety-action@v1.0.0
      with:
        api-key: ${{ secrets.SAFETY_API_KEY }}
        output: 'json'
        output-file: 'safety-report.json'

    - name: Run Bandit (Python security linter)
      run: |
        pip install bandit
        bandit -r . -f json -o bandit-report.json || true

    - name: Upload security reports
      uses: actions/upload-artifact@v3
      with:
        name: security-reports
        path: |
          safety-report.json
          bandit-report.json

